"""
src/enterprise/assets_config.py
Defines the ShopEasy enterprise archetype — a realistic simulated e-commerce
company with 30 assets spanning Production, Staging, Development, and Corporate
environments.

This is the single source of truth for:
  - Department definitions
  - Asset inventory (servers, databases, laptops, network appliances)
  - Software tags used for realistic CVE-to-asset matching

Criticality levels:  LOW | MEDIUM | HIGH | VERY_HIGH | CRITICAL
Business impact:     1 (minimal) → 10 (catastrophic)
"""

# ─────────────────────────────────────────────────────────────
# DEPARTMENTS
# ─────────────────────────────────────────────────────────────
DEPARTMENTS = [
    {"department_name": "Payments & Finance",   "lead_contact": "payments-lead@shopeasy.com"},
    {"department_name": "Core Engineering",     "lead_contact": "engineering-lead@shopeasy.com"},
    {"department_name": "IT Infrastructure",    "lead_contact": "infra-lead@shopeasy.com"},
    {"department_name": "Security Operations",  "lead_contact": "security-lead@shopeasy.com"},
    {"department_name": "Human Resources",      "lead_contact": "hr-lead@shopeasy.com"},
    {"department_name": "Data & Analytics",     "lead_contact": "data-lead@shopeasy.com"},
    {"department_name": "DevOps",               "lead_contact": "devops-lead@shopeasy.com"},
]

# ─────────────────────────────────────────────────────────────
# ASSETS
# Each asset has:
#   asset_id, asset_name, asset_type, criticality,
#   internet_exposure, business_impact_score (1-10),
#   department_name, ip_address, installed_software (tags),
#   environment, description
# ─────────────────────────────────────────────────────────────
ASSETS = [

    # ── PRODUCTION: PAYMENT & FINANCE ────────────────────────
    {
        "asset_id": "ASSET-001",
        "asset_name": "Payment Processing Server",
        "asset_type": "Server",
        "criticality": "CRITICAL",
        "internet_exposure": True,
        "business_impact_score": 10,
        "department_name": "Payments & Finance",
        "ip_address": "10.0.1.10",
        "installed_software": "java,spring,stripe,openssl,tls,nginx,payment,pci,encryption,tomcat",
        "environment": "Production",
        "description": "Handles all customer payment transactions. PCI-DSS scoped. Breach = regulatory fines + reputational damage.",
    },
    {
        "asset_id": "ASSET-002",
        "asset_name": "Financial Reporting Database",
        "asset_type": "Database",
        "criticality": "VERY_HIGH",
        "internet_exposure": False,
        "business_impact_score": 9,
        "department_name": "Payments & Finance",
        "ip_address": "10.0.1.11",
        "installed_software": "postgresql,sql,database,oracle,jdbc,encryption,backup",
        "environment": "Production",
        "description": "Stores financial transaction history and reporting data. Audit trail for regulators.",
    },

    # ── PRODUCTION: CORE ENGINEERING ─────────────────────────
    {
        "asset_id": "ASSET-003",
        "asset_name": "Customer Database Server",
        "asset_type": "Database",
        "criticality": "CRITICAL",
        "internet_exposure": False,
        "business_impact_score": 10,
        "department_name": "Core Engineering",
        "ip_address": "10.0.2.10",
        "installed_software": "mysql,postgresql,sql,database,redis,storage,encryption,pii,gdpr",
        "environment": "Production",
        "description": "Stores PII for all 2M+ customers. GDPR scoped. Breach = massive fines + class-action lawsuits.",
    },
    {
        "asset_id": "ASSET-004",
        "asset_name": "Public Web Server",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": True,
        "business_impact_score": 8,
        "department_name": "Core Engineering",
        "ip_address": "10.0.2.11",
        "installed_software": "nginx,apache,http,https,react,node,javascript,php,web,html,ssl,tls",
        "environment": "Production",
        "description": "Serves the public-facing ShopEasy storefront. Downtime = direct revenue loss.",
    },
    {
        "asset_id": "ASSET-005",
        "asset_name": "Authentication & SSO Server",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": True,
        "business_impact_score": 9,
        "department_name": "Core Engineering",
        "ip_address": "10.0.2.12",
        "installed_software": "oauth,jwt,keycloak,ldap,saml,sso,kerberos,auth,session,openid,mfa",
        "environment": "Production",
        "description": "Central authentication for all users and internal services. Compromise = full account takeover.",
    },
    {
        "asset_id": "ASSET-006",
        "asset_name": "Product Catalogue API Server",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": True,
        "business_impact_score": 7,
        "department_name": "Core Engineering",
        "ip_address": "10.0.2.13",
        "installed_software": "nodejs,express,api,rest,json,nginx,http,javascript,graphql",
        "environment": "Production",
        "description": "Serves product listing and search API to the storefront and mobile apps.",
    },
    {
        "asset_id": "ASSET-007",
        "asset_name": "Order Management System",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": False,
        "business_impact_score": 8,
        "department_name": "Core Engineering",
        "ip_address": "10.0.2.14",
        "installed_software": "java,spring,microservices,kafka,rabbitmq,queue,postgresql",
        "environment": "Production",
        "description": "Manages order lifecycle from cart to fulfilment. Internal service only.",
    },
    {
        "asset_id": "ASSET-008",
        "asset_name": "Notification & Email Server",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": True,
        "business_impact_score": 5,
        "department_name": "Core Engineering",
        "ip_address": "10.0.2.15",
        "installed_software": "postfix,sendmail,smtp,email,mailserver,exim,spf,dkim",
        "environment": "Production",
        "description": "Sends order confirmations, password resets, and marketing emails.",
    },

    # ── PRODUCTION: IT INFRASTRUCTURE ────────────────────────
    {
        "asset_id": "ASSET-009",
        "asset_name": "Load Balancer / API Gateway",
        "asset_type": "Network",
        "criticality": "HIGH",
        "internet_exposure": True,
        "business_impact_score": 8,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.3.10",
        "installed_software": "nginx,haproxy,ssl,tls,http,proxy,load balancer,gateway,openssl",
        "environment": "Production",
        "description": "Entry point for all inbound traffic. Handles SSL termination and routing.",
    },
    {
        "asset_id": "ASSET-010",
        "asset_name": "VPN Gateway",
        "asset_type": "Network",
        "criticality": "HIGH",
        "internet_exposure": True,
        "business_impact_score": 7,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.3.11",
        "installed_software": "vpn,openvpn,ipsec,ssl,tunnel,cisco,palo alto,wireguard,network",
        "environment": "Production",
        "description": "Remote access gateway for staff and third-party partners.",
    },
    {
        "asset_id": "ASSET-011",
        "asset_name": "Internal DNS Server",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 5,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.3.12",
        "installed_software": "bind,dns,named,network,resolver,zone",
        "environment": "Production",
        "description": "Internal DNS resolution for all enterprise services.",
    },
    {
        "asset_id": "ASSET-012",
        "asset_name": "Network Attached Storage (NAS)",
        "asset_type": "Storage",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 5,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.3.13",
        "installed_software": "samba,nfs,smb,storage,nas,file,backup,synology",
        "environment": "Production",
        "description": "Centralised file storage for teams and backup targets.",
    },
    {
        "asset_id": "ASSET-013",
        "asset_name": "Backup & Recovery Server",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 6,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.3.14",
        "installed_software": "backup,veeam,bacula,rsync,storage,recovery,encryption",
        "environment": "Production",
        "description": "Manages automated backups for all production databases and servers.",
    },

    # ── PRODUCTION: DATA & ANALYTICS ─────────────────────────
    {
        "asset_id": "ASSET-014",
        "asset_name": "Analytics Data Warehouse",
        "asset_type": "Database",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 6,
        "department_name": "Data & Analytics",
        "ip_address": "10.0.4.10",
        "installed_software": "snowflake,bigquery,redshift,spark,hadoop,sql,analytics,etl,airflow",
        "environment": "Production",
        "description": "Stores aggregated business intelligence data. Used for dashboards and reports.",
    },
    {
        "asset_id": "ASSET-015",
        "asset_name": "ML Model Serving API",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 5,
        "department_name": "Data & Analytics",
        "ip_address": "10.0.4.11",
        "installed_software": "python,flask,fastapi,tensorflow,pytorch,sklearn,docker,model,mlflow",
        "environment": "Production",
        "description": "Hosts recommendation and fraud detection ML models consumed by the storefront.",
    },

    # ── PRODUCTION: SECURITY OPERATIONS ──────────────────────
    {
        "asset_id": "ASSET-016",
        "asset_name": "SIEM & Log Management Server",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": False,
        "business_impact_score": 7,
        "department_name": "Security Operations",
        "ip_address": "10.0.5.10",
        "installed_software": "elasticsearch,splunk,kibana,logstash,siem,logging,monitor,security",
        "environment": "Production",
        "description": "Centralised security event logging and monitoring. Tampering = blind spot for attacks.",
    },
    {
        "asset_id": "ASSET-017",
        "asset_name": "Vulnerability Scanner Host",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 4,
        "department_name": "Security Operations",
        "ip_address": "10.0.5.11",
        "installed_software": "nessus,openvas,tenable,qualys,scanner,security,nmap",
        "environment": "Production",
        "description": "Runs scheduled vulnerability scans across the enterprise network.",
    },

    # ── STAGING ENVIRONMENT ───────────────────────────────────
    {
        "asset_id": "ASSET-018",
        "asset_name": "Staging Web Server",
        "asset_type": "Server",
        "criticality": "LOW",
        "internet_exposure": True,
        "business_impact_score": 3,
        "department_name": "Core Engineering",
        "ip_address": "10.0.6.10",
        "installed_software": "nginx,apache,http,https,react,node,javascript,web,staging",
        "environment": "Staging",
        "description": "Pre-production staging environment for QA testing.",
    },
    {
        "asset_id": "ASSET-019",
        "asset_name": "Staging Database",
        "asset_type": "Database",
        "criticality": "LOW",
        "internet_exposure": False,
        "business_impact_score": 2,
        "department_name": "Core Engineering",
        "ip_address": "10.0.6.11",
        "installed_software": "mysql,postgresql,sql,database,staging",
        "environment": "Staging",
        "description": "Contains anonymised/synthetic data for staging tests.",
    },

    # ── DEVELOPMENT ENVIRONMENT ───────────────────────────────
    {
        "asset_id": "ASSET-020",
        "asset_name": "CI/CD Build Server",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 4,
        "department_name": "DevOps",
        "ip_address": "10.0.7.10",
        "installed_software": "jenkins,gitlab,github,ci,cd,docker,kubernetes,build,pipeline,python,java",
        "environment": "Development",
        "description": "Runs automated builds and deployments. Supply-chain risk if compromised.",
    },
    {
        "asset_id": "ASSET-021",
        "asset_name": "Container Orchestration Cluster (K8s)",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": False,
        "business_impact_score": 5,
        "department_name": "DevOps",
        "ip_address": "10.0.7.11",
        "installed_software": "kubernetes,docker,container,helm,k8s,pod,orchestration,etcd",
        "environment": "Development",
        "description": "Development Kubernetes cluster. Shared by multiple engineering teams.",
    },
    {
        "asset_id": "ASSET-022",
        "asset_name": "Developer Workstation Pool",
        "asset_type": "Laptop",
        "criticality": "LOW",
        "internet_exposure": False,
        "business_impact_score": 3,
        "department_name": "Core Engineering",
        "ip_address": "10.0.7.50",
        "installed_software": "windows,linux,macos,chrome,firefox,browser,vscode,git,python,java,nodejs",
        "environment": "Development",
        "description": "Developer laptops and workstations. Could be entry point via phishing.",
    },
    {
        "asset_id": "ASSET-023",
        "asset_name": "Test / QA Server",
        "asset_type": "Server",
        "criticality": "LOW",
        "internet_exposure": False,
        "business_impact_score": 2,
        "department_name": "DevOps",
        "ip_address": "10.0.7.20",
        "installed_software": "selenium,pytest,jest,test,qa,staging,docker,python",
        "environment": "Development",
        "description": "Automated and manual QA testing environment.",
    },
    {
        "asset_id": "ASSET-024",
        "asset_name": "Developer Secrets Manager",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": False,
        "business_impact_score": 8,
        "department_name": "DevOps",
        "ip_address": "10.0.7.30",
        "installed_software": "vault,hashicorp,secrets,pki,certificate,encryption,key,token",
        "environment": "Development",
        "description": "HashiCorp Vault storing API keys, DB credentials, certificates. High-value target.",
    },

    # ── CORPORATE / HR ────────────────────────────────────────
    {
        "asset_id": "ASSET-025",
        "asset_name": "HR & Payroll System",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": False,
        "business_impact_score": 8,
        "department_name": "Human Resources",
        "ip_address": "10.0.8.10",
        "installed_software": "sap,workday,hr,payroll,employee,pii,ldap,active directory,windows",
        "environment": "Production",
        "description": "Employee PII, salary, and payroll data. GDPR/DPDPA scoped.",
    },
    {
        "asset_id": "ASSET-026",
        "asset_name": "Corporate Email Server",
        "asset_type": "Server",
        "criticality": "MEDIUM",
        "internet_exposure": True,
        "business_impact_score": 6,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.8.11",
        "installed_software": "exchange,outlook,smtp,email,microsoft,office365,postfix,imap,pop3",
        "environment": "Corporate",
        "description": "Enterprise email system. Primary phishing / BEC attack surface.",
    },
    {
        "asset_id": "ASSET-027",
        "asset_name": "Employee Endpoint Fleet",
        "asset_type": "Laptop",
        "criticality": "LOW",
        "internet_exposure": False,
        "business_impact_score": 3,
        "department_name": "IT Infrastructure",
        "ip_address": "10.0.8.50",
        "installed_software": "windows,office,chrome,firefox,browser,endpoint,antivirus,zoom,teams",
        "environment": "Corporate",
        "description": "Non-technical staff laptops. Common ransomware / phishing entry point.",
    },
    {
        "asset_id": "ASSET-028",
        "asset_name": "ERP System (SAP)",
        "asset_type": "Server",
        "criticality": "HIGH",
        "internet_exposure": False,
        "business_impact_score": 8,
        "department_name": "Payments & Finance",
        "ip_address": "10.0.8.20",
        "installed_software": "sap,erp,oracle,finance,accounting,supply chain,windows,java",
        "environment": "Production",
        "description": "Enterprise resource planning system for finance and operations.",
    },

    # ── CLOUD / EXTERNAL SERVICES ─────────────────────────────
    {
        "asset_id": "ASSET-029",
        "asset_name": "Cloud Storage Bucket (S3/GCS)",
        "asset_type": "Cloud",
        "criticality": "HIGH",
        "internet_exposure": True,
        "business_impact_score": 8,
        "department_name": "IT Infrastructure",
        "ip_address": None,
        "installed_software": "aws,s3,gcs,azure,cloud,storage,bucket,iam,object,terraform",
        "environment": "Production",
        "description": "Cloud object storage for user-uploaded files and media assets. Misconfiguration risk.",
    },
    {
        "asset_id": "ASSET-030",
        "asset_name": "CDN Edge Nodes",
        "asset_type": "Network",
        "criticality": "MEDIUM",
        "internet_exposure": True,
        "business_impact_score": 5,
        "department_name": "IT Infrastructure",
        "ip_address": None,
        "installed_software": "cloudflare,cdn,edge,cache,nginx,http,ssl,tls,web",
        "environment": "Production",
        "description": "Content delivery network for static assets. DDoS mitigation layer.",
    },
]
